
export const WISHLIST_REQUEST = "WISHLIST_REQUEST";
export const WISHLIST_GET_SUCCESS = "WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAILURE = "WISHLIST_GET_FAILURE";
export const WISHLIST_ADD_ITEM_SUCCESS = "WISHLIST_ADD_ITEM_SUCCESS";
export const WISHLIST_ADD_ITEM_FAILURE = "WISHLIST_ADD_ITEM_FAILURE";
export const WISHLIST_DELETE_ITEM_SUCCESS = "WISHLIST_DELETE_ITEM_SUCCESS";
export const WISHLIST_DELETE_ITEM_FAILURE = "WISHLIST_DELETE_ITEM_FAILURE";
export const WISHLIST_LOG_OUT = "WISHLIST_LOG_OUT";

export const PUT_DATA_SUCCESS = "PUT_DATA_SUCCESS";
export const PUT_DATA_FAILURE = "PUT_DATA_FAILURE";
export const LOAD_DATA = "LOAD_DATA";

export const INCREMENT = "INCREMENT";
export const INCREMENT_IF_ODD = "INCREMENT_IF_ODD";
export const DECREMENT = "DECREMENT";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";



